#!/bin/bash

# Compare the output of configuration scripts with the actual files

file=${1#files}
rpath=${file/\//}

export LANG=C

pkg=$(pacman -Qo $file | sed -E 's|.* is owned by ([^ ]+) ([^ ]+)$|\1-\2|')

#tar -xf /var/cache/pacman/pkg/$pkg*.tar.zst $rpath

diff $rpath $file
